//
// Generated by JTB 1.3.2
//

package symbol.syntaxtree;

/**
 * Grammar production:
 * f0 -> "boolean"
 */
public class BooleanType implements Node {
   public NodeToken f0;

   public BooleanType(NodeToken n0) {
      f0 = n0;
   }

   public BooleanType() {
      f0 = new NodeToken("boolean");
   }

   public void accept(symbol.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(symbol.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(symbol.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(symbol.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

