//
// Generated by JTB 1.3.2
//

package syntaxtree_piglet;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(visitor_piglet.Visitor v);
   public <R,A> R accept(visitor_piglet.GJVisitor<R,A> v, A argu);
   public <R> R accept(visitor_piglet.GJNoArguVisitor<R> v);
   public <A> void accept(visitor_piglet.GJVoidVisitor<A> v, A argu);
}

